import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#003640',
        'on-primary': '#1000a9',
        'surface-variant': '#273647',
        'inverse-surface': '#d4e4fa',
        'error-container': '#93000a',
        primary: '#c0c1ff',
        'surface-container-highest': '#273647',
        'on-tertiary-fixed-variant': '#005321',
        'on-primary-fixed': '#07006c',
        secondary: '#4cd7f6',
        'on-tertiary-container': '#003111',
        'primary-fixed': '#e1e0ff',
        'tertiary-fixed-dim': '#4ae176',
        background: '#051424',
        surface: '#051424',
        'on-primary-fixed-variant': '#2f2ebe',
        'primary-fixed-dim': '#c0c1ff',
        'inverse-primary': '#494bd6',
        'secondary-fixed': '#acedff',
        tertiary: '#4ae176',
        error: '#ffb4ab',
        'surface-container-lowest': '#010f1f',
        'on-secondary-fixed-variant': '#004e5c',
        'secondary-fixed-dim': '#4cd7f6',
        'on-surface-variant': '#c7c4d7',
        'surface-container': '#122131',
        'surface-container-high': '#1c2b3c',
        'on-error': '#690005',
        'on-tertiary': '#003915',
        'on-secondary-container': '#00424e',
        'surface-tint': '#c0c1ff',
        outline: '#908fa0',
        'outline-variant': '#464554',
        'surface-container-low': '#0d1c2d',
        'secondary-container': '#03b5d3',
        'on-error-container': '#ffdad6',
        'surface-dim': '#051424',
        'on-secondary-fixed': '#001f26',
        'surface-bright': '#2c3a4c',
        'primary-container': '#8083ff',
        'on-tertiary-fixed': '#002109',
        'on-background': '#d4e4fa',
        'tertiary-container': '#00a74b',
        'on-primary-container': '#0d0096',
        'on-surface': '#d4e4fa',
        'inverse-on-surface': '#233143',
        'tertiary-fixed': '#6bff8f',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-tablet': '1.5rem',
        'gutter-desktop': '1.5rem',
        gutter: '1.25rem',
        margin: '1rem',
        'space-xl': '2.5rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-xs': '0.25rem',
        'space-lg': '1.5rem',
        'margin-desktop': '2rem',
      },
      fontFamily: {
        'body-sm': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'display-lg': ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'headline-xl-mobile': ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'label-sm': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'headline-sm': ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'display-lg-mobile': ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'headline-xl': ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'data-metric': ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'display-lg-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'data-metric': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};

export default config;
